# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ubuntu/fpgaProject/MyIR7020/Vivado2022.2/HispeedADC4CH/HispeedADC4CH.srcs/sources_1/bd/design_1/ip/design_1_LTC2324_sample_0_0/design_1_LTC2324_sample_0_0.xci
# IP: The module: 'design_1_LTC2324_sample_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ubuntu/fpgaProject/MyIR7020/Vivado2022.2/HispeedADC4CH/HispeedADC4CH.gen/sources_1/bd/design_1/ip/design_1_LTC2324_sample_0_0/src/afifo/afifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] -quiet

# XDC: /home/ubuntu/fpgaProject/MyIR7020/Vivado2022.2/HispeedADC4CH/HispeedADC4CH.gen/sources_1/bd/design_1/ip/design_1_LTC2324_sample_0_0/src/afifo/afifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ubuntu/fpgaProject/MyIR7020/Vivado2022.2/HispeedADC4CH/HispeedADC4CH.gen/sources_1/bd/design_1/ip/design_1_LTC2324_sample_0_0/src/afifo/afifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: /home/ubuntu/fpgaProject/MyIR7020/Vivado2022.2/HispeedADC4CH/HispeedADC4CH.srcs/sources_1/bd/design_1/ip/design_1_LTC2324_sample_0_0/design_1_LTC2324_sample_0_0.xci
# IP: The module: 'design_1_LTC2324_sample_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ubuntu/fpgaProject/MyIR7020/Vivado2022.2/HispeedADC4CH/HispeedADC4CH.gen/sources_1/bd/design_1/ip/design_1_LTC2324_sample_0_0/src/afifo/afifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] -quiet

# XDC: /home/ubuntu/fpgaProject/MyIR7020/Vivado2022.2/HispeedADC4CH/HispeedADC4CH.gen/sources_1/bd/design_1/ip/design_1_LTC2324_sample_0_0/src/afifo/afifo.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ubuntu/fpgaProject/MyIR7020/Vivado2022.2/HispeedADC4CH/HispeedADC4CH.gen/sources_1/bd/design_1/ip/design_1_LTC2324_sample_0_0/src/afifo/afifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
